package com.dennis.omni_orders.dto;

// Enum representing order status (PENDING, PROCESSING, etc.)
import com.dennis.omni_orders.model.OrderStatus;

// Swagger annotation for documenting response models
import io.swagger.v3.oas.annotations.media.Schema;

import java.time.LocalDateTime;

/**
 * OrderResponse (DTO)
 *
 * Purpose:
 * This class defines the structure of the data returned to the client
 * when an order is requested.
 *
 * Why this exists (IMPORTANT):
 * - Prevents exposing internal entity structure directly
 * - Controls exactly what fields are returned in API responses
 * - Allows flexibility to change internal database structure later
 *   without breaking the API contract
 *
 * This is the "output" version of an Order.
 */
@Schema(description = "Response body for an order")
public class OrderResponse {

    /**
     * Order ID
     *
     * This is generated by the database.
     * Clients never send this — they only receive it.
     */
    @Schema(description = "Unique order ID", example = "1")
    private Long id;

    /**
     * Item name
     *
     * Returned exactly as stored.
     */
    @Schema(description = "Name of the ordered item", example = "Nike Shoes")
    private String itemName;

    /**
     * Quantity
     */
    @Schema(description = "Quantity ordered", example = "2")
    private int quantity;

    /**
     * Order status
     *
     * Represents the current stage of the order lifecycle.
     */
    @Schema(description = "Current order status", example = "PENDING")
    private OrderStatus status;

    /**
     * Created timestamp
     *
     * Set automatically when the order is first saved.
     */
    @Schema(description = "Timestamp when the order was created", example = "2026-03-28T18:45:00")
    private LocalDateTime createdAt;

    /**
     * Updated timestamp
     *
     * Updated whenever the order is modified.
     */
    @Schema(description = "Timestamp when the order was last updated", example = "2026-03-28T19:00:00")
    private LocalDateTime updatedAt;

    /**
     * Default constructor
     *
     * Required by:
     * - Jackson (for serialization/deserialization if needed)
     */
    public OrderResponse() {
    }

    /**
     * Full constructor
     *
     * Used when mapping from Entity → DTO in the service layer
     *
     * Example:
     * return new OrderResponse(...);
     */
    public OrderResponse(Long id, String itemName, int quantity, OrderStatus status,
                         LocalDateTime createdAt, LocalDateTime updatedAt) {
        this.id = id;
        this.itemName = itemName;
        this.quantity = quantity;
        this.status = status;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    /**
     * Getters
     *
     * Used when converting Java object → JSON response
     */
    public Long getId() {
        return id;
    }

    public String getItemName() {
        return itemName;
    }

    public int getQuantity() {
        return quantity;
    }

    public OrderStatus getStatus() {
        return status;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    /**
     * Setters
     *
     * Typically not used much for response DTOs,
     * but included for completeness and flexibility.
     */
    public void setId(Long id) {
        this.id = id;
    }

    public void setItemName(String itemName) {
        this.itemName = itemName;
    }

    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    public void setStatus(OrderStatus status) {
        this.status = status;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }
}